function=SHAPE2NETWORK
 shpi=C:\projects\Roanoke\MasterNetwork\Master_Node.SHP
 shpi=C:\projects\Roanoke\MasterNetwork\Master_Link.SHP
 neto=C:\projects\Roanoke\MasterNetwork\Master_highway.net
 PointNodeNumField="N"
 AnodeField=A
 BnodeField=B
 LevelField=""
 ClearABValues=T
 DirectionOption=1
 DirectionField=""
 AddDistanceField=Y
 DistanceScale=2.22
 NodeGroupingLimit=1
 StartingNewNode=1000
 HighestZone=270
 
 endfunction
